use std::path::{Path, PathBuf};

use gix_hash::ObjectId;
use gix_testtools::size_ok;

pub use gix_testtools::{Result, scripted_fixture_read_only};

mod access;
mod entry;
mod file;
mod fs;
mod fuzzed;
mod init;

static SHA1_TO_SHA256_HASHES: std::sync::LazyLock<std::collections::HashMap<&str, &str>> =
    std::sync::LazyLock::new(|| {
        [
            (
                "496d6428b9cf92981dc9495211e6e1120fb6f2ba",
                "5f6f307bcc469c02acba4f7da42d8d4defdda8209777fe732956f1e2fa0db3ff",
            ),
            (
                "4b825dc642cb6eb9a060e54bf8d69288fbee4904",
                "6ef19b41225c5369f1c104d45d8d85efa9b057b53b14b4b9b939dd74decc5321",
            ),
            (
                "72d53f787d86a932a25a8537cee236d81846a8f1",
                "645f454faab2cb984a331efafb76345242aa1d2029dff13a63935a31752f05ee",
            ),
            (
                "e69de29bb2d1d6434b8b29ae775ad8c2e48c5391",
                "473a0f4c3be8a93681a267e3b1e9a7dcda1185436fe141f7749120a303721813",
            ),
        ]
        .into()
    });

/// Convert a hexadecimal hash into its corresponding `ObjectId` or _panic_.
pub fn hex_to_id(hex: &str) -> ObjectId {
    match gix_testtools::object_hash() {
        gix_hash::Kind::Sha1 => ObjectId::from_hex(hex.as_bytes()).expect("40 bytes hex"),
        gix_hash::Kind::Sha256 => ObjectId::from_hex(
            SHA1_TO_SHA256_HASHES
                .get(hex)
                .unwrap_or_else(|| panic!("SHA-1 {hex} wasn't mapped to SHA-256 yet"))
                .as_bytes(),
        )
        .expect("64 bytes hex"),
        _ => unimplemented!(),
    }
}

/// Get an object database handle for `objects_dir`, respecting the hash kind configured for tests.
pub fn odb_at(objects_dir: impl Into<PathBuf>) -> Result<gix_odb::Handle> {
    Ok(gix_odb::at_opts(
        objects_dir,
        Vec::new(),
        gix_odb::store::init::Options {
            object_hash: gix_testtools::object_hash(),
            ..Default::default()
        },
    )?)
}

pub fn fixture_index_path(name: &str) -> PathBuf {
    let dir = gix_testtools::scripted_fixture_read_only(Path::new("make_index").join(name).with_extension("sh"))
        .expect("script works");
    dir.join(".git").join("index")
}

pub fn fixture_index_path_needs_archive(name: &str) -> PathBuf {
    let dir = gix_testtools::scripted_fixture_read_only_needs_archive(
        Path::new("make_index").join(name).with_extension("sh"),
    )
    .expect("script works");
    dir.join(".git").join("index")
}

pub fn loose_file_path(name: &str) -> PathBuf {
    gix_testtools::fixture_path(Path::new("loose_index").join(name).with_extension("git-index"))
}

#[test]
fn size_of_entry() {
    let actual = std::mem::size_of::<gix_index::Entry>();
    let sha1 = 80;
    let sha256_extra = 16;
    let expected = sha1 + sha256_extra;
    assert!(
        size_ok(actual, expected),
        "the size of this structure should not change unexpectedly: {actual} <~ {expected}"
    );
}

#[test]
fn size_of_entry_time() {
    // The reason we have our own time is that it is half the size.
    let ent_actual = std::mem::size_of::<gix_index::entry::stat::Time>();
    let ent_expected = 8;
    assert!(
        size_ok(ent_actual, ent_expected),
        "the size of this structure should not change unexpectedly: {ent_actual} <~ {ent_expected}"
    );
    let ft_actual = std::mem::size_of::<filetime::FileTime>();
    let ft_expected = 16;
    assert!(
        size_ok(ft_actual, ft_expected),
        "we will want to know if the size of this structure changes: {ft_actual} <~ {ft_expected}"
    );
}

enum Fixture {
    Generated(&'static str),
    Loose(&'static str),
}

impl Fixture {
    pub fn to_path(&self) -> PathBuf {
        match self {
            Fixture::Generated(name) => fixture_index_path(name),
            Fixture::Loose(name) => loose_file_path(name),
        }
    }
    pub fn to_name(&self) -> &'static str {
        match self {
            Fixture::Generated(name) | Fixture::Loose(name) => name,
        }
    }

    pub fn open(&self) -> gix_index::File {
        let object_hash = match self {
            // Generated fixtures are generated by `gix_testtools`, respecting
            // `GIX_TEST_FIXTURE_HASH`.
            Fixture::Generated(_) => gix_testtools::object_hash(),
            // Loose fixtures are not generated by `gix_testtools`. They contain hard-coded SHA-1
            // hashes.
            Fixture::Loose(_) => gix_hash::Kind::Sha1,
        };
        gix_index::File::at(self.to_path(), object_hash, false, Default::default())
            .expect("fixtures are always readable")
    }
}
