ARG TARGET

FROM ghcr.io/cross-rs/${TARGET}:latest

ARG TARGET

RUN set -uC && \
    apt_suffix= && \
    if target_arch="$(dpkg-architecture --host-type "$TARGET" --query DEB_HOST_ARCH)"; then \
        dpkg --add-architecture "$target_arch" && \
        apt_suffix=":$target_arch"; \
    fi && \
    apt-get update && \
    apt-get install --no-install-recommends -y software-properties-common && \
    add-apt-repository -y ppa:git-core/ppa && \
    apt-get update && \
    apt-get install --no-install-recommends -y "libc6$apt_suffix" "libcurl3-gnutls$apt_suffix" \
        "libexpat1$apt_suffix" "libpcre2-8-0$apt_suffix" "zlib1g$apt_suffix" "perl$apt_suffix" \
        liberror-perl git-man patch jq && \
    apt-get download "git$apt_suffix" && \
    dpkg --ignore-depends="liberror-perl$apt_suffix" -i ./git[-_]*.deb && \
    apt-get purge --autoremove software-properties-common && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    if test -f /android-runner; then \
        sed -i.orig 's/^export LD_PRELOAD=/test "${NO_PRELOAD_CXX:-0}" != 0 || &/' \
            /android-runner; \
    fi && \
    git config --system gitoxide.imaginary.arbitraryVariable arbitraryValue
