FROM ghcr.io/cross-rs/s390x-unknown-linux-gnu:latest

RUN set -xC && \
    apt-get update && \
    apt-get install apt-transport-https && \
    echo 'deb https://ppa.launchpadcontent.net/git-core/ppa/ubuntu xenial main' > \
        /etc/apt/sources.list.d/git-core-ubuntu-ppa-xenial.list && \
    apt-key adv --keyserver keyserver.ubuntu.com \
        --recv-keys F911AB184317630C59970973E363C90F8F1B6217 && \
    apt-get update && \
    apt-get install --no-install-recommends -y git && \
    rm -rf /var/lib/apt/lists/* && \
    git config --system gitoxide.imaginary.arbitraryVariable arbitraryValue
