blank_issues_enabled: false
contact_links:
  - name: Propose a feature
    url: https://github.com/GitoxideLabs/gitoxide/discussions/categories/feature-proposal
    about: Search existing proposals or start a discussion to hash out new features
