#!/usr/bin/env bash
set -eu -o pipefail

# This script is a placeholder for a script generated by the
# `create-diff-cases` subcommand of `internal-tools`. The placeholder does
# nothing except making the associated test trivially pass.
#
# See the `gix-diff/tests/README.md` file for more information.
