#!/usr/bin/env bash
set -eu -o pipefail

# This script is a placeholder for a script generated by the
# `create-diff-cases` subcommand of `internal-tools`. The placeholder does
# nothing except making the associated test trivially pass.
#
# ## Usage
#
# Follow these instructions to generate a file containing sliders:
# https://github.com/mhagger/diff-slider-tools/blob/b59ed13d7a2a6cfe14a8f79d434b6221cc8b04dd/README.md?plain=1#L122-L146
#
# Run `create-diff-cases` to create the script in `gix-diff/tests/fixtures/`.
# The script will be called `make_diff_for_sliders_repo.sh` and it will
# overwrite the placeholder.
#
# ```
# # run inside `gitoxide`
# cargo run --package internal-tools -- create-diff-cases --sliders-file $PATH_TO_DIFF_SLIDER_TOOLS/corpus/git.sliders --worktree-dir $PATH_TO_DIFF_SLIDER_TOOLS/corpus/git.git/ --destination-dir gix-diff/tests/fixtures/
# ```
#
# Run `cargo test sliders -- --nocapture` inside `gix-diff/tests` to run the
# actual tests.
